/**
 *  Copyright 2021 Peter Nerg
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.dmonix.prometheus

import io.prometheus.client.Gauge

import scala.concurrent.{ExecutionContext, Future}

/**
 * Adds functions related to the ''Gauge'' class.
 * @since 1.0
 */
object Gauges {

  /**
   * Automatically increases/decreases the gauge around the provided function block.
   * {{{
   *   measure(gauge){
   *     //code goes here
   *   }
   * }}}
   * @param gauge The gauge to increase/decrease
   * @param block The block of code to execute/measure
   * @tparam T
   * @return
   * @since 1.0
   */
  def measure[T](gauge:Gauge)(block: => T): T = {
    gauge.inc()
    try {
      block
    } finally {
      gauge.dec()
    }
  }


  /**
   * Automatically increases/decreases the gauge around the provided function block.
   * {{{
   *   measure(gauge){
   *     //code goes here
   *   }
   * }}}
   * @param gauge The gauge to increase/decrease
   * @param block The block of code to execute/measure
   * @tparam T
   * @return
   * @since 1.0
   */
  def measure[T](gauge:Gauge.Child)(block: => T): T = {
    gauge.inc()
    try {
      block
    } finally {
      gauge.dec()
    }
  }

  /**
   * Automatically increases/decreases the gauge around the future generated by the function block.
   * Increases before the future is created and decreases as a side effect of completing the future.
   * {{{
   *   val fut = measureAsync(gauge) {
   *     Future {
   *       //code goes here
   *     }
   *   }
   * }}}
   * @param gauge The gauge to increase/decrease
   * @param block The function returning a Future which to measure
   * @param ec
   * @tparam T
   * @return
   * @since 1.0
   */
  def measureAsync[T](gauge:Gauge)(block: => Future[T])(implicit ec:ExecutionContext): Future[T] = {
    gauge.inc()
    block.andThen{case _ => gauge.dec()}(ec)
  }

  /**
   * Automatically increases/decreases the gauge around the future generated by the function block.
   * Increases before the future is created and decreases as a side effect of completing the future.
   * {{{
   *   val fut = measureAsync(gauge) {
   *     Future {
   *       //code goes here
   *     }
   *   }
   * }}}
   * @param gauge The gauge to increase/decrease
   * @param block The function returning a Future which to measure
   * @param ec
   * @tparam T
   * @return
   * @since 1.0
   */
  def measureAsync[T](gauge:Gauge.Child)(block: => Future[T])(implicit ec:ExecutionContext): Future[T] = {
    gauge.inc()
    block.andThen{case _ => gauge.dec()}(ec)
  }

  /**
   * Resets the gauge to '0'
   * @param gauge The gauge to reset
   * @since 1.0
   */
  def reset(gauge:Gauge):Unit = gauge.set(0)

  /**
   * Resets the gauge to '0'
   * @param gauge The gauge to reset
   * @since 1.0
   */
  def reset(gauge:Gauge.Child):Unit = gauge.set(0)
}
